// frontend/components/admin/SettingsManager.vue
<script setup lang="ts">
import { RefreshCw, Save } from "lucide-vue-next";

interface Setting {
  key: string;
  value: unknown;
  updatedAt: string;
  draft: string;
}

/** Rótulos amigáveis para as chaves conhecidas — porte de
 * src/features/admin/components/SettingsManager.tsx (menos
 * `taxa-acidentes.target`, indicador removido). */
const LABELS: Record<string, string> = {
  "rdo.target": "RDO — meta de aprovação (fração)",
  "idp.target": "IDP/Cronograma — meta (fração)",
  "idp.excludedDisciplines": "IDP — disciplinas excluídas",
  "idp.excludedUnits": "IDP — unidades excluídas",
  "rnc.maxPrazoDias": "RNC — prazo máximo (dias)",
  "fiveS.target": "5S — meta (fração)",
  "fiveS.excludedUnits": "5S — unidades excluídas",
};

const api = useApi();
const items = ref<Setting[]>([]);
const loading = ref(true);
const busy = ref(false);
const message = ref("");

function serialize(value: unknown) {
  return typeof value === "string" ? value : JSON.stringify(value, null, 2);
}
function parse(value: string) {
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

async function load() {
  loading.value = true;
  try {
    items.value = (await api.get<{ items: Array<Omit<Setting, "draft">> }>("/configuracoes")).items.map((item) => ({
      ...item,
      draft: serialize(item.value),
    }));
  } catch (cause) {
    message.value = cause instanceof Error ? cause.message : "Erro ao carregar configurações.";
  } finally {
    loading.value = false;
  }
}

async function save(item: Setting) {
  busy.value = true;
  message.value = "";
  try {
    await api.patch("/configuracoes", { key: item.key, value: parse(item.draft) });
    message.value = `"${item.key}" salvo.`;
  } catch (cause) {
    message.value = cause instanceof Error ? cause.message : `Falha ao salvar "${item.key}".`;
  } finally {
    busy.value = false;
  }
}

onMounted(load);
</script>

<template>
  <div class="space-y-4">
    <div class="flex items-center justify-between">
      <p v-if="message" class="text-sm text-neutralbrand">{{ message }}</p>
      <div class="ml-auto" />
      <Button variant="outline" size="icon" aria-label="Atualizar" @click="load">
        <RefreshCw class="size-4" />
      </Button>
    </div>

    <p v-if="loading" class="text-sm text-neutralbrand">Carregando…</p>
    <div v-else class="space-y-3">
      <Card v-for="item in items" :key="item.key">
        <CardContent class="space-y-2 pt-5">
          <div class="flex items-baseline justify-between gap-2">
            <Label :for="`set-${item.key}`" class="normal-case tracking-normal text-sm font-semibold text-brand-dark">
              {{ LABELS[item.key] ?? item.key }}
            </Label>
            <code class="text-xs text-neutralbrand">{{ item.key }}</code>
          </div>
          <div class="flex gap-2">
            <Textarea :id="`set-${item.key}`" v-model="item.draft" class="min-h-9 flex-1 font-mono" />
            <Button :disabled="busy" @click="save(item)"><Save class="size-4" /> Salvar</Button>
          </div>
        </CardContent>
      </Card>
    </div>

    <p class="text-xs text-neutralbrand">
      Valores são interpretados como JSON quando possível (ex.: <code>0.80</code>,
      <code>["SP","CSC"]</code>); caso contrário, como texto. Metas em fração (0.80 = 80%).
    </p>
  </div>
</template>

// src/features/admin/components/SettingsManager.tsx
"use client";

import { useCallback, useEffect, useState } from "react";

interface Setting {
  key: string;
  value: unknown;
}

/** Rótulos amigáveis para as chaves conhecidas. */
const LABELS: Record<string, string> = {
  "idp.target": "IDP/Cronograma — meta (fração)",
  "idp.excludedDisciplines": "IDP — disciplinas excluídas",
  "fiveS.target": "5S — meta (fração)",
  "rnc.maxPrazoDias": "RNC — prazo máximo (dias)",
  "taxa-acidentes.target": "Taxa de Acidentes — meta",
  "fiveS.excludedUnits": "5S — unidades excluídas",
};

export function SettingsManager() {
  const [settings, setSettings] = useState<Setting[]>([]);
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [savingKey, setSavingKey] = useState<string | null>(null);
  const [msg, setMsg] = useState<string | null>(null);
  const [canEdit, setCanEdit] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/configuracoes");
      if (!res.ok) {
        setError("Falha ao carregar as configurações.");
        return;
      }
      const data = (await res.json()) as { items: Setting[] };
      setSettings(data.items);
      const d: Record<string, string> = {};
      for (const s of data.items) {
        d[s.key] =
          typeof s.value === "string"
            ? s.value
            : JSON.stringify(s.value, null, 0);
      }
      setDrafts(d);
    } catch {
      setError("Falha ao carregar as configurações.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  async function save(key: string) {
    setSavingKey(key);
    setMsg(null);
    try {
      let value: unknown;
      const raw = drafts[key] ?? "";
      // Tenta interpretar como JSON (número, array, objeto); senão, texto.
      try {
        value = JSON.parse(raw);
      } catch {
        value = raw;
      }
      const res = await fetch("/api/configuracoes", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ key, value }),
      });
      if (res.ok) {
        setMsg(`"${key}" salvo.`);
      } else if (res.status === 403) {
        setCanEdit(false);
        setMsg("Apenas administradores podem alterar configurações.");
      } else {
        setMsg(`Falha ao salvar "${key}".`);
      }
    } finally {
      setSavingKey(null);
    }
  }

  if (loading) return <p className="text-sm text-neutralbrand">Carregando…</p>;
  if (error) return <p className="text-sm text-danger">{error}</p>;

  return (
    <div className="space-y-4">
      {msg ? <p className="text-sm text-neutralbrand">{msg}</p> : null}
      <div className="space-y-3">
        {settings.map((s) => (
          <div
            key={s.key}
            className="rounded-lg border border-neutralbrand/30 bg-white p-4"
          >
            <div className="mb-1 flex items-baseline justify-between gap-2">
              <label
                className="text-sm font-semibold text-brand-dark"
                htmlFor={`set-${s.key}`}
              >
                {LABELS[s.key] ?? s.key}
              </label>
              <code className="text-xs text-neutralbrand">{s.key}</code>
            </div>
            <div className="flex gap-2">
              <input
                id={`set-${s.key}`}
                value={drafts[s.key] ?? ""}
                onChange={(e) =>
                  setDrafts((d) => ({ ...d, [s.key]: e.target.value }))
                }
                disabled={!canEdit}
                className="flex-1 rounded border border-neutralbrand/50 px-2 py-1 font-mono text-sm"
              />
              <button
                onClick={() => save(s.key)}
                disabled={savingKey === s.key || !canEdit}
                className="rounded bg-brand px-3 py-1 text-sm font-semibold text-white hover:bg-brand-dark disabled:opacity-50"
              >
                Salvar
              </button>
            </div>
          </div>
        ))}
      </div>
      <p className="text-xs text-neutralbrand">
        Valores são interpretados como JSON quando possível (ex.: <code>0.80</code>,{" "}
        <code>[&quot;SP&quot;,&quot;CSC&quot;]</code>); caso contrário, como texto.
        Metas em fração (0.80 = 80%).
      </p>
    </div>
  );
}
